from Classes import *
import pickle

# **********Bank Classes************
sbi_bank = Bank("State Bank Of India")
hdfc_bank = Bank("HDFC Bank Of India")
icici_bank = Bank("ICICI Bank")
union_bank = Bank("Union Bank Of India")
axis_bank = Bank("AXIS Bank")


# *********Branches of banks (5)*********
sbi_bank.add_branch("balanagar")
sbi_bank.add_branch("chityal")
sbi_bank.add_branch("karimnagar")
sbi_bank.add_branch("nalgonda")
sbi_bank.add_branch("medchal")

hdfc_bank.add_branch("hyderguda")
hdfc_bank.add_branch("koti")
hdfc_bank.add_branch("abids")
hdfc_bank.add_branch("bazaarghat")
hdfc_bank.add_branch("kachiguda")

icici_bank.add_branch("himayatnagar")
icici_bank.add_branch("nampally")
icici_bank.add_branch("begumpet")
icici_bank.add_branch("badichowdi")
icici_bank.add_branch("gachibowli")

union_bank.add_branch("banjarahills")
union_bank.add_branch("bowenpally")
union_bank.add_branch("chikkadapally")
union_bank.add_branch("dilsukhNagar")
union_bank.add_branch("gayatrinagar")

axis_bank.add_branch("rudraram")
axis_bank.add_branch("saifabad")
axis_bank.add_branch("ramkote")
axis_bank.add_branch("nuzividu")
axis_bank.add_branch("kukatpally")

# ******* Customers for each and every branch(10) **********

# SBI Branches Customers
sbi_bank.add_customer("balanagar", "Krisia", 14000)
sbi_bank.add_customer("balanagar", "Peyra", 12500)
sbi_bank.add_customer("balanagar", "kotia", 8900)
sbi_bank.add_customer("balanagar", "Lachlia", 27000)
sbi_bank.add_customer("balanagar", "Eissen", 28400)
sbi_bank.add_customer("balanagar", "Draya", 13600)
sbi_bank.add_customer("balanagar", "Janna", 37600)
sbi_bank.add_customer("balanagar", "Xandyr", 100780)
sbi_bank.add_customer("balanagar", "Rikia", 45600)
sbi_bank.add_customer("balanagar", "Frey", 23800)

sbi_bank.add_customer("chityal", "Brayan Swailes", 28770)
sbi_bank.add_customer("chityal", "Whitelaw Whitley", 67300)
sbi_bank.add_customer("chityal", "Octavio Brent", 27044)
sbi_bank.add_customer("chityal", "Alcot Townsend", 67300)
sbi_bank.add_customer("chityal", "Spence Sydney", 276400)
sbi_bank.add_customer("chityal", "Bozo Melton", 37600)
sbi_bank.add_customer("chityal", "Kastor Hornsby", 28770)
sbi_bank.add_customer("chityal", "Claudde Bentham", 56200)
sbi_bank.add_customer("chityal", "Silvestre Harrison", 67400)
sbi_bank.add_customer("chityal", "Darin Chatham", 6490)

sbi_bank.add_customer("karimnagar", "Willi Rodney", 28900)
sbi_bank.add_customer("karimnagar", "Verdell Barney", 78300)
sbi_bank.add_customer("karimnagar", "Nikolas Bristol", 17800)
sbi_bank.add_customer("karimnagar", "Chadwick Burbridge", 38700)
sbi_bank.add_customer("karimnagar", "Tibault Chatham", 56000)
sbi_bank.add_customer("karimnagar", "Per Blankley", 236500)
sbi_bank.add_customer("karimnagar", "Wolter Altham", 78400)
sbi_bank.add_customer("karimnagar", "Timothy Withers", 89302)
sbi_bank.add_customer("karimnagar", "Jeremias Bush", 78400)
sbi_bank.add_customer("karimnagar", "Stanmore Garfield", 12900)

sbi_bank.add_customer("nalgonda", "Claudine Colby", 23670)
sbi_bank.add_customer("nalgonda", "Silvina Byron", 78400)
sbi_bank.add_customer("nalgonda", "Berty Bradshaw", 12789)
sbi_bank.add_customer("nalgonda", "Lily Shelly", 45790)
sbi_bank.add_customer("nalgonda", "Kunigunde Abram", 124780)
sbi_bank.add_customer("nalgonda", "Dennise Hallewell", 23674)
sbi_bank.add_customer("nalgonda", "Xavierra Hayden", 28750)
sbi_bank.add_customer("nalgonda", "Silja Stansfield", 76590)
sbi_bank.add_customer("nalgonda", "Friederika Lancaster", 59099)
sbi_bank.add_customer("nalgonda", "Bryana Stanley", 78565)

sbi_bank.add_customer("medchal", "Ashton Atterton", 470990)
sbi_bank.add_customer("medchal", "Ronald Prescott", 54900)
sbi_bank.add_customer("medchal", "Brenton Peddle", 34500)
sbi_bank.add_customer("medchal", "Alphonsus Byron", 42900)
sbi_bank.add_customer("medchal", "Tybalt Thorp", 27800)
sbi_bank.add_customer("medchal", "Griswold Springfield", 67500)
sbi_bank.add_customer("medchal", "Donovan Clark", 45670)
sbi_bank.add_customer("medchal", "Jürgen Mendenhall", 376500)
sbi_bank.add_customer("medchal", "Jarred Soames", 65790)
sbi_bank.add_customer("medchal", "Vasco Kendall", 78560)

# HDFC Branches Customers **************************

hdfc_bank.add_customer("hyderguda", "Branson", 99780)
hdfc_bank.add_customer("hyderguda", "Kaylie Churchill", 54600)
hdfc_bank.add_customer("hyderguda", "Bobby Watt", 34600)
hdfc_bank.add_customer("hyderguda", "Cherine Outerbridge", 67500)
hdfc_bank.add_customer("hyderguda", "Renee Lester", 87564)
hdfc_bank.add_customer("hyderguda", "Lavernia Luxford", 789354)
hdfc_bank.add_customer("hyderguda", "Clementina Soames ", 67300)
hdfc_bank.add_customer("hyderguda", "Silvette Crompton", 36450)
hdfc_bank.add_customer("hyderguda", "Hidie Harrington", 62350)
hdfc_bank.add_customer("hyderguda", "Dania Chatham", 45630)

hdfc_bank.add_customer("koti", "Creighton Goodwin", 23560)
hdfc_bank.add_customer("koti", "Garan Colby", 654780)
hdfc_bank.add_customer("koti", "Jagger Cromwell", 35460)
hdfc_bank.add_customer("koti", "Enes Sydney", 456300)
hdfc_bank.add_customer("koti", "Jean-Luca Williams", 26489)
hdfc_bank.add_customer("koti", "Bodil Denholm", 65478)
hdfc_bank.add_customer("koti", "Garlan Ramsay", 65490)
hdfc_bank.add_customer("koti", "Fernando Lancaster", 675890)
hdfc_bank.add_customer("koti", "Sadddique Currington", 35460)
hdfc_bank.add_customer("koti", "Giso Smit", 65290)

hdfc_bank.add_customer("abids", "Parkley Lester", 23560)
hdfc_bank.add_customer("abids", "Jarvey Hastings", 56490)
hdfc_bank.add_customer("abids", "Roland Myerscough", 25369)
hdfc_bank.add_customer("abids", "Dorkas Smith", 536490)
hdfc_bank.add_customer("abids", "Germain Brent", 564389)
hdfc_bank.add_customer("abids", "Kendall Tindall", 25604)
hdfc_bank.add_customer("abids", "Gerrit Williams", 53200)
hdfc_bank.add_customer("abids", "Elmer Keats", 45270)
hdfc_bank.add_customer("abids", "Harri Smither", 42389)
hdfc_bank.add_customer("abids", "Harland Alden", 67490)

hdfc_bank.add_customer("bazaarghat", "Eudokia Braxton", 64590)
hdfc_bank.add_customer("bazaarghat", "Eartha Birkenhead", 78300)
hdfc_bank.add_customer("bazaarghat", "Cindy Elton", 526300)
hdfc_bank.add_customer("bazaarghat", "Trine Padley", 56380)
hdfc_bank.add_customer("bazaarghat", "Sofie Stonebridge", 52620)
hdfc_bank.add_customer("bazaarghat", "Makenzie Harding", 61700)
hdfc_bank.add_customer("bazaarghat", "Tessa Harley", 16700)
hdfc_bank.add_customer("bazaarghat", "Lilith Dukes", 27390)
hdfc_bank.add_customer("bazaarghat", "Ronny Alvingham", 516200)
hdfc_bank.add_customer("bazaarghat", "Chelsey Mildenhall", 125630)

hdfc_bank.add_customer("kachiguda", "Beardsley Brown", 326740)
hdfc_bank.add_customer("kachiguda", "Johnson Ashley", 76290)
hdfc_bank.add_customer("kachiguda", "Paulus Altham", 526380)
hdfc_bank.add_customer("kachiguda", "Paxon Addington", 67309)
hdfc_bank.add_customer("kachiguda", "Gerome Brooks", 526390)
hdfc_bank.add_customer("kachiguda", "Durant Sheldon", 56300)
hdfc_bank.add_customer("kachiguda", "Raghnall Springfield", 67190)
hdfc_bank.add_customer("kachiguda", "Christien Paddle", 67250)
hdfc_bank.add_customer("kachiguda", "Beal Ward", 65340)
hdfc_bank.add_customer("kachiguda", "Shaw Ridley", 54600)

# ICICI Branches Customers **************************

icici_bank.add_customer("himayatnagar", "Krisia", 143400)
icici_bank.add_customer("himayatnagar", "Peyra", 14500)
icici_bank.add_customer("himayatnagar", "kotia", 8900)
icici_bank.add_customer("himayatnagar", "Lachlia", 27000)
icici_bank.add_customer("himayatnagar", "Eissen", 284300)
icici_bank.add_customer("himayatnagar", "Draya", 13600)
icici_bank.add_customer("himayatnagar", "Janna", 37630)
icici_bank.add_customer("himayatnagar", "Xandyr", 100780)
icici_bank.add_customer("himayatnagar", "Rikia", 45600)
icici_bank.add_customer("himayatnagar", "Frey", 238450)

icici_bank.add_customer("nampally", "Brayan", 287560)
icici_bank.add_customer("nampally", "Whitley", 673400)
icici_bank.add_customer("nampally", "Octavio Brent", 27044)
icici_bank.add_customer("nampally", "Alcot ", 67300)
icici_bank.add_customer("nampally", "Spence ", 2764670)
icici_bank.add_customer("nampally", "Melton", 37600)
icici_bank.add_customer("nampally", "Hornsby", 283470)
icici_bank.add_customer("nampally", "Claudde ", 56200)
icici_bank.add_customer("nampally", "Silvestre ", 67400)
icici_bank.add_customer("nampally", "Darin ", 6490)

icici_bank.add_customer("begumpet", "Willi Rodney", 28900)
icici_bank.add_customer("begumpet", "Verdell", 78300)
icici_bank.add_customer("begumpet", "Nikolas", 677800)
icici_bank.add_customer("begumpet", "Chadwick", 38700)
icici_bank.add_customer("begumpet", " Chatham", 56000)
icici_bank.add_customer("begumpet", "Per", 236500)
icici_bank.add_customer("begumpet", "Wolter", 786700)
icici_bank.add_customer("begumpet", "Timothy", 89302)
icici_bank.add_customer("begumpet", "Jeremias", 78400)
icici_bank.add_customer("begumpet", " Garfield", 12900)

icici_bank.add_customer("badichowdi", "Claudine", 23670)
icici_bank.add_customer("badichowdi", "Silvina Byron", 787800)
icici_bank.add_customer("badichowdi", "Berty ", 12789)
icici_bank.add_customer("badichowdi", "Lily ", 45790)
icici_bank.add_customer("badichowdi", "Kunigunde Abram", 124780)
icici_bank.add_customer("badichowdi", "Hallewell", 2335674)
icici_bank.add_customer("badichowdi", "Xavierra Hayden", 28750)
icici_bank.add_customer("badichowdi", "Stansfield", 76590)
icici_bank.add_customer("badichowdi", "Friederika", 59099)
icici_bank.add_customer("badichowdi", "Stanley", 78565)

icici_bank.add_customer("gachibowli", "Ashton", 470990)
icici_bank.add_customer("gachibowli", "Ronald", 549500)
icici_bank.add_customer("gachibowli", "Brenton Peddle", 34500)
icici_bank.add_customer("gachibowli", "Byron", 42900)
icici_bank.add_customer("gachibowli", "Tybalt", 278020)
icici_bank.add_customer("gachibowli", "Griswold", 67500)
icici_bank.add_customer("gachibowli", "Clark", 45670)
icici_bank.add_customer("gachibowli", "Jürgen", 3726500)
icici_bank.add_customer("gachibowli", "Jarred Soames", 65790)
icici_bank.add_customer("gachibowli", "Kendall", 785760)

# UNION Branches Customers **************************

union_bank.add_customer("banjarahills", "Branson", 239780)
union_bank.add_customer("banjarahills", "Kaylie Churchill", 546454)
union_bank.add_customer("banjarahills", "Bobby Watt", 343870)
union_bank.add_customer("banjarahills", "Cherine", 36374)
union_bank.add_customer("banjarahills", "Renee Lester", 27462)
union_bank.add_customer("banjarahills", "Lavernia", 826478)
union_bank.add_customer("banjarahills", "Clementina Soames ", 67624)
union_bank.add_customer("banjarahills", "Silvette", 27467)
union_bank.add_customer("banjarahills", "Hidie Harrington", 24435)
union_bank.add_customer("banjarahills", "Dania", 45636)

union_bank.add_customer("bowenpally", "Creighton", 235460)
union_bank.add_customer("bowenpally", "Garan Colby", 6544540)
union_bank.add_customer("bowenpally", "Jagger", 3545760)
union_bank.add_customer("bowenpally", "Enes Sydney", 4426300)
union_bank.add_customer("bowenpally", "Jean-Luca ", 245489)
union_bank.add_customer("bowenpally", "Bodil Denholm", 654688)
union_bank.add_customer("bowenpally", "Garlan Ramsay", 89375)
union_bank.add_customer("bowenpally", "Fernando", 6748890)
union_bank.add_customer("bowenpally", "Sadddique", 892764)
union_bank.add_customer("bowenpally", "Giso Smit", 37857)

union_bank.add_customer("chikkadapally", "Parkley Lester", 23560)
union_bank.add_customer("chikkadapally", "Jarvey Hastings", 56490)
union_bank.add_customer("chikkadapally", "Roland", 25369)
union_bank.add_customer("chikkadapally", "Dorkasith", 536490)
union_bank.add_customer("chikkadapally", "Germain", 564389)
union_bank.add_customer("chikkadapally", "Kendall", 25604)
union_bank.add_customer("chikkadapally", "Gerrit", 53200)
union_bank.add_customer("chikkadapally", "Elmer Keats", 45270)
union_bank.add_customer("chikkadapally", "Harri", 42389)
union_bank.add_customer("chikkadapally", "Harland Alden", 67490)

union_bank.add_customer("dilsukhNagar", "Eudokia Braxton", 6470990)
union_bank.add_customer("dilsukhNagar", "Eartha", 78300)
union_bank.add_customer("dilsukhNagar", "Cindy Elton", 52630)
union_bank.add_customer("dilsukhNagar", "Trine", 565480)
union_bank.add_customer("dilsukhNagar", "Sofie", 52620)
union_bank.add_customer("dilsukhNagar", "Makenzie Harding", 61700)
union_bank.add_customer("dilsukhNagar", "Tessa Harley", 167090)
union_bank.add_customer("dilsukhNagar", "Lilithkes", 270990)
union_bank.add_customer("dilsukhNagar", "Ronny", 516200)
union_bank.add_customer("dilsukhNagar", "Chelsey", 12946630)

union_bank.add_customer("gayatrinagar", "Beardsley", 326740)
union_bank.add_customer("gayatrinagar", "Johnson", 76290)
union_bank.add_customer("gayatrinagar", "Altham", 526380)
union_bank.add_customer("gayatrinagar", "Paxon Addington", 67309)
union_bank.add_customer("gayatrinagar", "Gerome", 526390)
union_bank.add_customer("gayatrinagar", "Durant Sheldon", 56300)
union_bank.add_customer("gayatrinagar", "Raghnall", 67190)
union_bank.add_customer("gayatrinagar", "Christien Paddle", 67250)
union_bank.add_customer("gayatrinagar", "Beal Ward", 65340)
union_bank.add_customer("gayatrinagar", "Shaw Ridley", 54600)

# AXIS Branches Customers **************************

axis_bank.add_customer("rudraram", "Michael", 354673)
axis_bank.add_customer("rudraram", "Johhny", 25615)
axis_bank.add_customer("rudraram", "Kanne", 98253)
axis_bank.add_customer("rudraram", "Jordan", 78152)
axis_bank.add_customer("rudraram", "Kanam", 987265)
axis_bank.add_customer("rudraram", "Knvindha", 982534)
axis_bank.add_customer("rudraram", "Angela", 846632)
axis_bank.add_customer("rudraram", "Stunnerd", 126352)
axis_bank.add_customer("rudraram", "Jonamy", 452562)
axis_bank.add_customer("rudraram", "Kussai", 675645)

axis_bank.add_customer("saifabad", "Funnete", 652783)
axis_bank.add_customer("saifabad", "Hunnay", 56172)
axis_bank.add_customer("saifabad", "German Steve", 887921)
axis_bank.add_customer("saifabad", "Sholeye", 29382)
axis_bank.add_customer("saifabad", "Kanmen", 78723)
axis_bank.add_customer("saifabad", "Jordan Kanish", 478383)
axis_bank.add_customer("saifabad", "Quert Kane", 735528)
axis_bank.add_customer("saifabad", "Williamson", 487432)
axis_bank.add_customer("saifabad", "John", 687793)
axis_bank.add_customer("saifabad", "Fedbika", 256578)

axis_bank.add_customer("ramkote", "Kanne", 67329)
axis_bank.add_customer("ramkote", "Hunnai", 84157)
axis_bank.add_customer("ramkote", "Loaiky", 2325557)
axis_bank.add_customer("ramkote", "Kaiily", 265247)
axis_bank.add_customer("ramkote", "Humano", 889111)
axis_bank.add_customer("ramkote", "Qwerty", 900000)
axis_bank.add_customer("ramkote", "KaneSon", 627334)
axis_bank.add_customer("ramkote", "Lilly", 7246200)
axis_bank.add_customer("ramkote", "Poperry", 2893230)
axis_bank.add_customer("ramkote", "Loilo", 100002)

axis_bank.add_customer("nuzividu", "Enteian", 27800)
axis_bank.add_customer("nuzividu", "Antony", 47627)
axis_bank.add_customer("nuzividu", "Knanneli", 67463)
axis_bank.add_customer("nuzividu", "Broster", 36746)
axis_bank.add_customer("nuzividu", "Barak", 36737)
axis_bank.add_customer("nuzividu", "Chinni", 97832)
axis_bank.add_customer("nuzividu", "Meyalam", 79973)
axis_bank.add_customer("nuzividu", "Hojn", 3939725)
axis_bank.add_customer("nuzividu", "Kiae", 85792)
axis_bank.add_customer("nuzividu", "Jeff", 823926)

axis_bank.add_customer("kukatpally", "Chotia", 462427)
axis_bank.add_customer("kukatpally", "Unnai", 386800)
axis_bank.add_customer("kukatpally", "Feffhoz", 3637600)
axis_bank.add_customer("kukatpally", "Sachin", 32235)
axis_bank.add_customer("kukatpally", "Michael", 82682)
axis_bank.add_customer("kukatpally", "Unaity", 1272736)
axis_bank.add_customer("kukatpally", "Gosey", 27470)
axis_bank.add_customer("kukatpally", "Wunart", 390000)
axis_bank.add_customer("kukatpally", "Chubbed", 79338)
axis_bank.add_customer("kukatpally", "Jeffy", 383598)

#   **************** End *********************


def dumping_data():
    with open("bank_data.pkl", 'wb') as bank_data:
        pickle.dump(sbi_bank, bank_data)
        pickle.dump(hdfc_bank, bank_data)
        pickle.dump(icici_bank, bank_data)
        pickle.dump(union_bank, bank_data)
        pickle.dump(axis_bank, bank_data)





# sbi_bank = Bank("State Bank Of India")
# hdfc_bank = Bank("HDFC Bank Of India")
# icici_bank = Bank("ICICI Bank")
# union_bank = Bank("Union Bank Of India")
# axis_bank = Bank("AXIS Bank")


# bank1 = Bank("National Bank")
# bank1.add_branch("something")
# bank1.add_customer("something", "Vishwanth", 200)
# bank1.add_customer("something", "hima", 280)
# bank1.add_customer("something", "rishi", 190)
# bank1.add_customer_transaction("something", "Vishwanth", 789)
# bank1.add_customer_transaction("something", "rishi", 689)
#
# bank1.list_branch_customers("something", True)
# bank1.list_branch_customers("something", False)



# branch1 = Branch("SBI")
# branch1.new_customer("Vishwanth", 200)
# branch1.new_customer("Vishwanth", 302)
# branch1.new_customer("Hima", 23)
# branch1.list_customers()
# branch1.add_customer_transaction("Vishwanth", 9999)
# branch1.list_customers()


#
# c1 = Customer("Vishwanth", 20)
# print(c1.get_transactions())
# print(c1.get_name())
# c1.add_transaction(30)
# print(c1.get_transactions())
# c2 = Customer("Hima", 340)
# c2.add_transaction(47)
# print(c2.get_transactions())
# print(c2.get_name())
# print(c1.get_name())
